# Generated by Django 5.0.6 on 2024-06-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardio_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('cardio_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_log.cardiotype')),
            ],
        ),
    ]
