# Generated by Django 5.0.6 on 2024-06-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardioLog',
            new_name='CardioLogModel',
        ),
        migrations.RenameModel(
            old_name='CardioType',
            new_name='CardioTypeModel',
        ),
    ]
