# Generated by Django 5.0.6 on 2024-06-30 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0002_rename_cardiolog_cardiologmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiologmodel',
            name='duration',
            field=models.DurationField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
