# Generated by Django 5.0.6 on 2024-06-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0003_cardiologmodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiologmodel',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
