# Generated by Django 5.0.6 on 2024-06-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0005_alter_cardiologmodel_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiologmodel',
            name='duration',
        ),
    ]
