# Generated by Django 5.0.6 on 2024-06-30 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0006_remove_cardiologmodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiologmodel',
            name='duration',
            field=models.DateTimeField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
