# Generated by Django 5.0.6 on 2024-06-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0007_cardiologmodel_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiologmodel',
            name='duration',
        ),
    ]
