# Generated by Django 5.0.6 on 2024-06-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0009_remove_cardiologmodel_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardioLogModel',
        ),
    ]
