# Generated by Django 5.0.6 on 2024-06-30 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0012_delete_cardiologmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('cardio_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_log.cardiotypemodel')),
            ],
        ),
    ]
