# Generated by Django 5.0.6 on 2024-06-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0013_cardiologmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardioLogModel',
        ),
    ]
